# Generated by Django 6.0.2 on 2026-02-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("features", models.JSONField(default=list)),
                ("keywords", models.JSONField(default=list)),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("blog_post_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Resume Project",
                "verbose_name_plural": "Resume Projects",
                "ordering": ["title"],
            },
        ),
    ]
