# Generated by Django 6.0.2 on 2026-08-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_links_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeproject",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="resumeproject",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="resumeproject",
            name="links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of {"label": "...", "url": "..."} objects',
            ),
        ),
    ]
