# Generated by Django 6.0.2 on 2026-03-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryphoto",
            name="source",
        ),
    ]
