# Generated by Django 6.0.7 on 2026-08-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='related_project_label',
            field=models.CharField(blank=True, help_text="Text shown for the link, e.g. 'Update on aviationdocs.net' or 'View source on GitHub'", max_length=200),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='related_project_url',
            field=models.URLField(blank=True, help_text='Link to a project this post is about, e.g. a GitHub repo or project site'),
        ),
    ]
