# Generated by Django 6.0.7 on 2026-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_related_project_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='related_project_label',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='related_project_url',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='github_url',
            field=models.URLField(blank=True, help_text="Link to the project's GitHub repo"),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='site_label',
            field=models.CharField(blank=True, help_text="Text shown for the site link, e.g. 'Update on aviationdocs.net'", max_length=200),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='site_url',
            field=models.URLField(blank=True, help_text="Link to the project's live site"),
        ),
    ]
