# Generated by Django 6.0.2 on 2026-08-23 04:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blogpage_related_project_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("paragraph", 3),
                    ("image", 6),
                    ("carousel", 8),
                    ("video", 9),
                    ("code", 12),
                    ("quote", 14),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                            ],
                            "template": "blog/blocks/paragraph_block.html",
                        },
                    ),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("wagtail.blocks.StructBlock", [[("images", 7)]], {}),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Paste a YouTube or Vimeo URL",
                            "icon": "media",
                            "label": "Video Embed",
                            "template": "blog/blocks/video_block.html",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                                ("typescript", "TypeScript"),
                                ("java", "Java"),
                                ("C", "C"),
                                ("bash", "Bash"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("json", "JSON"),
                                ("sql", "SQL"),
                            ]
                        },
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 10), ("code", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional — who said it", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 11), ("attribution", 13)]],
                        {},
                    ),
                },
            ),
        ),
    ]
