# Generated by Django 6.0.2 on 2026-02-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0005_remove_gpx_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adventurepage",
            options={"ordering": ["-date_start"], "verbose_name": "Adventure Post"},
        ),
        migrations.AlterField(
            model_name="adventurepage",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Manual override. Leave blank to use value computed from uploaded activity files.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adventurepage",
            name="elevation_gain_m",
            field=models.IntegerField(
                blank=True,
                help_text="Manual override. Leave blank to use value computed from uploaded activity files.",
                null=True,
            ),
        ),
    ]
