# Generated by Django 6.0.2 on 2026-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adventures", "0007_alter_adventurepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventurepage",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("hiking", "Hiking"),
                    ("cycling", "Cycling"),
                    ("running", "Running"),
                    ("skiing", "Skiing"),
                    ("climbing", "Climbing"),
                    ("mountaineering", "Mountaineering"),
                    ("kayaking", "Kayaking"),
                    ("sailing", "Sailing"),
                    ("other", "Other"),
                ],
                default="hiking",
                max_length=20,
            ),
        ),
    ]
