# Generated by Django 6.0.2 on 2026-02-26 10:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('full_name', models.CharField(max_length=255)),
                ('professional_title', models.CharField(max_length=255)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('contact_links', wagtail.fields.StreamField([('contact_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. GitHub, LinkedIn, Email'}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional CSS icon class', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1), ('icon_class', 2)]], {})})),
                ('body', wagtail.fields.StreamField([('work_experience', 6), ('education', 9), ('skill_group', 12), ('certification', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Jan 2020'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Mar 2023 or Present'}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.blocks.ListBlock', (0,), {'label': 'Achievements'}), 6: ('wagtail.blocks.StructBlock', [[('company', 0), ('role', 0), ('location', 1), ('start_date', 2), ('end_date', 3), ('description', 4), ('achievements', 5)]], {'group': 'Experience'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Sep 2016'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Jun 2020 or Present'}), 9: ('wagtail.blocks.StructBlock', [[('institution', 0), ('degree', 0), ('location', 1), ('start_date', 7), ('end_date', 8), ('notes', 1)]], {'group': 'Education'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Languages, Frameworks'}), 11: ('wagtail.blocks.ListBlock', (0,), {}), 12: ('wagtail.blocks.StructBlock', [[('group_name', 10), ('skills', 11)]], {'group': 'Skills'}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Nov 2022'}), 14: ('wagtail.blocks.URLBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('name', 0), ('issuer', 0), ('date', 13), ('url', 14)]], {'group': 'Certifications'})})),
            ],
            options={
                'verbose_name': 'Resume Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
