# Generated by Django 6.0.2 on 2026-02-27 19:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumepage",
            name="contact_links",
            field=wagtail.fields.StreamField(
                [("contact_link", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g. GitHub, LinkedIn, Email"},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Use this or Email, not both", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Use this or URL, not both", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional CSS icon class", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("url", 1), ("email", 2), ("icon_class", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
